### ISSUE TITLE
Database relational diagram to repository

### ISSUE THREAD

**Issue by rick-astral-cat** [zoftko/reflovex#7]
Migrations can explain database structure and relations for developers, but a diagram is helpful and explain everything better than words. This diagram is made with [drawio](https://www.drawio.com/) will be updated at the same time migrations are required.
[Database file proposal](https://drive.google.com/drive/folders/1pW5XYY_L94-JtGspiqnenmxMIuD0J-Px?usp=drive_link)

**Comment by crazybolillo** [comment]
Posting a snapshot of the db model to make comments on it:
![Screenshot from 2023-08-28 09-12-44](https://github.com/zoftko/reflovex/assets/40015596/ae4b407c-a2e9-41be-a016-cfab53185b63)

- Perhaps personal preference but I think we should use singular names, so for example, boards -> board
- Instead of `cicles` we should probably have a table called `session`. Each session represents a single process of reflowing the board (ramp-up, reflow and cooling). I think said table should only have:
    - board_id
    - date
- We can just rename `cicles` to `session` and drop the status field (or maybe not?,  but I don't know what its use will be)
- Table `measures` is fine. We should add a `UNIQUE (id, sequence)` constraint to it. Although the correct plural for it is `measurements`. If we use singular nouns, `measure` or `reading` would be fine.
- `stages` should not be related to cicles or readings, they are just a configuration helper.
- We need a new table called `profile`. Each `profile` should probably have three stages linked to it.
- We  can also probably drop the stage table, and just add the following columns for profile:
    - ramp up gradient (celsius per second)
    - soak temperature
    - soak time
    - reflow gradient
    - reflow peak temp
    - reflow max time (failsafe, if peak temp is never reached, max time to stay during reflow)
    - cooldown gradient (celsius per second)

**Comment by crazybolillo** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/RSS_Components_of_a_Profile1.svg/800px-RSS_Components_of_a_Profile1.svg.png)

This image shows the reasoning behind the proposed columns for `profile`.

https://en.wikipedia.org/wiki/Reflow_soldering

**Comment by rick-astral-cat** [comment]
I use plural names because Laravel propose this on table names also because every model yo create is in an singular mode and Laravel relates automatically the table on database with the plural name (Laravel conventions).

We can rename cycles to sessions and I propose state for a description of the final state of the session, like a note if necessary for example board not welded or something else (we can remove it).

Measurements its fine, and I don't understand what do you mean with UNIQUE constraint on ID. On every Laravel migration by default increments and timestamps properties are added so every table has a unsigned big integer ID with auto index and unique. Also, created_at and modified_at columns are added so every model event fill this information automatically.

I put stages (profile) related because I consider every session (reflow cycle made) will have different parameters like you said in the image. Of this way you can retrieve the parameters of every singular session.  Do you propose an isolated profiles table?

**Comment by crazybolillo** [comment]
Makes sense. We should keep the plural names then. 

I think we should remove description from sessions. Maybe we can add it in the future (if the rp2040 supports it).

By UNIQUE I meant we cant have repeated sequences. So the combination of session id and sequence in measurements must be unique. 

The thing with making a profile related to a session is that you can't update the profile afterwards, plus you can get all the info by just looking at the measurements. No need to see what profile was used. 

Profile is more of a configuration, measurements are a historic.

**Comment by rick-astral-cat** [comment]
Then we keep plural names on database tables.
Changes were made to columns names an relations.
![Reflovex](https://github.com/zoftko/reflovex/assets/143054530/74354bf9-eee7-437e-9802-270ff8e29826)

**Comment by crazybolillo** [comment]
> Then we keep plural names on database tables. Changes were made to columns names an relations. ![Reflovex](https://user-images.githubusercontent.com/143054530/263899533-74354bf9-eee7-437e-9802-270ff8e29826.jpg)

Looks good. Will sessions also have the profile parameters that were used as extra columns? We can probably use an embeddable model to reuse the same columns for the profiles table and sessions.

**Comment by rick-astral-cat** [comment]
Yes, they will have those parameters. Embeddable models are not supported for Laravel (an extra package is required) so we'll set the columns on sessions table. So, finally this is the basic model database to start working.
![ReflovexDB](https://github.com/zoftko/reflovex/assets/143054530/196ef3bd-2cf0-48e9-abf5-f540d2aac29e)

**Comment by crazybolillo** [comment]
Yes sounds good. You can go ahead and make the PR.
